import type { Metadata } from 'next'
import { Inter, Roboto_Mono } from 'next/font/google'
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

const powerGrotesk = Roboto_Mono({ 
  subsets: ['latin'],
  variable: '--font-power-grotesk',
})

export const metadata: Metadata = {
  title: 'Anima Project - Automatically generated by Anima',
  description: 'A React project automatically generated by Anima using the Shadcn UI library',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${powerGrotesk.variable}`}>{children}</body>
    </html>
  )
}